// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.2

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type Skeleton2ServiceHTTPServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
}

func RegisterSkeleton2ServiceHTTPServer(s *http.Server, srv Skeleton2ServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/Skeleton2/Service/v1/Get", _Skeleton2Service_Get0_HTTP_Handler(srv))
}

func _Skeleton2Service_Get0_HTTP_Handler(srv Skeleton2ServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.service.v1.Skeleton2Service/Get")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Get(ctx, req.(*GetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReply)
		return ctx.Result(200, reply)
	}
}

type Skeleton2ServiceHTTPClient interface {
	Get(ctx context.Context, req *GetRequest, opts ...http.CallOption) (rsp *GetReply, err error)
}

type Skeleton2ServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSkeleton2ServiceHTTPClient(client *http.Client) Skeleton2ServiceHTTPClient {
	return &Skeleton2ServiceHTTPClientImpl{client}
}

func (c *Skeleton2ServiceHTTPClientImpl) Get(ctx context.Context, in *GetRequest, opts ...http.CallOption) (*GetReply, error) {
	var out GetReply
	pattern := "/Skeleton2/Service/v1/Get"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.service.v1.Skeleton2Service/Get"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
