// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Skeleton3ServiceClient is the client API for Skeleton3Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Skeleton3ServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
}

type skeleton3ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkeleton3ServiceClient(cc grpc.ClientConnInterface) Skeleton3ServiceClient {
	return &skeleton3ServiceClient{cc}
}

func (c *skeleton3ServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	out := new(GetReply)
	err := c.cc.Invoke(ctx, "/api.skeleton3.service.v1.Skeleton3Service/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Skeleton3ServiceServer is the server API for Skeleton3Service service.
// All implementations must embed UnimplementedSkeleton3ServiceServer
// for forward compatibility
type Skeleton3ServiceServer interface {
	Get(context.Context, *GetRequest) (*GetReply, error)
	mustEmbedUnimplementedSkeleton3ServiceServer()
}

// UnimplementedSkeleton3ServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSkeleton3ServiceServer struct {
}

func (UnimplementedSkeleton3ServiceServer) Get(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedSkeleton3ServiceServer) mustEmbedUnimplementedSkeleton3ServiceServer() {}

// UnsafeSkeleton3ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Skeleton3ServiceServer will
// result in compilation errors.
type UnsafeSkeleton3ServiceServer interface {
	mustEmbedUnimplementedSkeleton3ServiceServer()
}

func RegisterSkeleton3ServiceServer(s grpc.ServiceRegistrar, srv Skeleton3ServiceServer) {
	s.RegisterService(&Skeleton3Service_ServiceDesc, srv)
}

func _Skeleton3Service_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Skeleton3ServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.skeleton3.service.v1.Skeleton3Service/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Skeleton3ServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Skeleton3Service_ServiceDesc is the grpc.ServiceDesc for Skeleton3Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Skeleton3Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.skeleton3.service.v1.Skeleton3Service",
	HandlerType: (*Skeleton3ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Skeleton3Service_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/skeleton3/service/v1/service.proto",
}
