// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/robfig/cron/v3"
	"gl.king.im/king-lib/framework/test/skeleton/internal/conf"
	"gl.king.im/king-lib/framework/test/skeleton/internal/data"
	"gl.king.im/king-lib/framework/test/skeleton/internal/worker"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(server *conf.Server, confData *conf.Data, biz *conf.Biz, logger log.Logger) (cron.Job, func(), error) {
	client := data.NewBossEntCli(confData)
	job := worker.NewJobB(client)
	return job, func() {
	}, nil
}
