// Code generated by entc, DO NOT EDIT.

package demo

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gl.king.im/king-lib/framework/test/skeleton2/internal/data/ent/demo/predicate"
	"gl.king.im/king-lib/framework/test/skeleton2/internal/data/ent/demo/sometable"
)

// SomeTableDelete is the builder for deleting a SomeTable entity.
type SomeTableDelete struct {
	config
	hooks    []Hook
	mutation *SomeTableMutation
}

// Where appends a list predicates to the SomeTableDelete builder.
func (std *SomeTableDelete) Where(ps ...predicate.SomeTable) *SomeTableDelete {
	std.mutation.Where(ps...)
	return std
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (std *SomeTableDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(std.hooks) == 0 {
		affected, err = std.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SomeTableMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			std.mutation = mutation
			affected, err = std.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(std.hooks) - 1; i >= 0; i-- {
			if std.hooks[i] == nil {
				return 0, fmt.Errorf("demo: uninitialized hook (forgotten import demo/runtime?)")
			}
			mut = std.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, std.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (std *SomeTableDelete) ExecX(ctx context.Context) int {
	n, err := std.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (std *SomeTableDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: sometable.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: sometable.FieldID,
			},
		},
	}
	if ps := std.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, std.driver, _spec)
}

// SomeTableDeleteOne is the builder for deleting a single SomeTable entity.
type SomeTableDeleteOne struct {
	std *SomeTableDelete
}

// Exec executes the deletion query.
func (stdo *SomeTableDeleteOne) Exec(ctx context.Context) error {
	n, err := stdo.std.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sometable.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (stdo *SomeTableDeleteOne) ExecX(ctx context.Context) {
	stdo.std.ExecX(ctx)
}
